"""
compare_with_literature.py
==========================
Compare your ablation summary.csv against reference baselines from literature.

Edit Ablation_Study/literature_baselines.csv to add papers the client shared.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def main() -> int:
    project_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Compare results with literature baselines.")
    parser.add_argument(
        "--summary",
        type=Path,
        default=project_root / "Ablation_Study" / "results" / "summary.csv",
    )
    parser.add_argument(
        "--baselines",
        type=Path,
        default=project_root / "Ablation_Study" / "literature_baselines.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_root / "Ablation_Study" / "results" / "literature_comparison.csv",
    )
    args = parser.parse_args()

    if not args.summary.exists():
        print(f"Missing summary: {args.summary}")
        print("Run ablation experiments first.")
        return 1
    if not args.baselines.exists():
        print(f"Missing baselines: {args.baselines}")
        return 1

    ours = pd.read_csv(args.summary)
    refs = pd.read_csv(args.baselines)

    ours_rows = []
    for _, row in ours.iterrows():
        ours_rows.append({
            "source": "this_project",
            "reference": row.get("config_name", ""),
            "method": "ablation_config",
            "dataset": "CASME-II",
            "label_setup": "",
            "validation": "holdout",
            "accuracy": row.get("accuracy"),
            "macro_f1": row.get("macro_f1"),
            "notes": "Generated by MER Initial Project",
        })

    combined = pd.concat([refs, pd.DataFrame(ours_rows)], ignore_index=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(args.output, index=False)

    print(f"Comparison table written: {args.output}")
    print(f"  Reference papers: {len(refs)}")
    print(f"  Your configs:     {len(ours)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
